# Generated by Django 2.1.3 on 2019-01-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
